POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndvbmRlclllYXJzIiwiaWQiOiI2MDZhNTAwYjMxOGYzYTIxNzc1NGIwMmYiLCJpYXQiOjE2MTgwNjI1NzF9.s1Dt_2bk-famWAKy9k7OLWiAzDaC7lSGwpae0uQYyZU

{
  "title": "Middleware test blogpost",
  "author": "M Ware",
  "url": "https://middleurl.com/",
  "likes": 1
}