POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndvbmRlclllYXJzIiwiaWQiOiI2MDZhNTAwYjMxOGYzYTIxNzc1NGIwMmYiLCJpYXQiOjE2MTg4NDgxNDd9.N6C9MdLRIGoohSyX3Dtmf-y7rbkmr2OUyraqtrZFgCQ

{
  "title": "Middleware test3 blogpost",
  "author": "M Ware4",
  "url": "https://middle4url.com/",
  "likes": 4
}